// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollectionCard: typeof import('./components/CollectionCard.vue')['default']
    FavoriteCard: typeof import('./components/FavoriteCard.vue')['default']
    PhotoCard: typeof import('./components/PhotoCard.vue')['default']
    PhotoInfoChartCard: typeof import('./components/PhotoInfoChartCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDetailCard: typeof import('./components/SearchDetailCard.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
  }
}
